#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LuckyDraw")]
	public partial class LuckyDrawDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLUCKY_DRAW(LUCKY_DRAW instance);
    partial void UpdateLUCKY_DRAW(LUCKY_DRAW instance);
    partial void DeleteLUCKY_DRAW(LUCKY_DRAW instance);
    partial void InsertLUCKY_DRAW_PROGRAME(LUCKY_DRAW_PROGRAME instance);
    partial void UpdateLUCKY_DRAW_PROGRAME(LUCKY_DRAW_PROGRAME instance);
    partial void DeleteLUCKY_DRAW_PROGRAME(LUCKY_DRAW_PROGRAME instance);
    partial void InsertLUCKY_DRAW_PROGRAME_HISTORY(LUCKY_DRAW_PROGRAME_HISTORY instance);
    partial void UpdateLUCKY_DRAW_PROGRAME_HISTORY(LUCKY_DRAW_PROGRAME_HISTORY instance);
    partial void DeleteLUCKY_DRAW_PROGRAME_HISTORY(LUCKY_DRAW_PROGRAME_HISTORY instance);
    partial void InsertLUCKY_DRAW_KOKAKU(LUCKY_DRAW_KOKAKU instance);
    partial void UpdateLUCKY_DRAW_KOKAKU(LUCKY_DRAW_KOKAKU instance);
    partial void DeleteLUCKY_DRAW_KOKAKU(LUCKY_DRAW_KOKAKU instance);
    partial void InsertLUCKY_DRAW_MEISAI(LUCKY_DRAW_MEISAI instance);
    partial void UpdateLUCKY_DRAW_MEISAI(LUCKY_DRAW_MEISAI instance);
    partial void DeleteLUCKY_DRAW_MEISAI(LUCKY_DRAW_MEISAI instance);
    #endregion
		
		public LuckyDrawDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LuckyDrawDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LuckyDrawDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LuckyDrawDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LUCKY_DRAW> LUCKY_DRAWs
		{
			get
			{
				return this.GetTable<LUCKY_DRAW>();
			}
		}
		
		public System.Data.Linq.Table<LUCKY_DRAW_PROGRAME> LUCKY_DRAW_PROGRAMEs
		{
			get
			{
				return this.GetTable<LUCKY_DRAW_PROGRAME>();
			}
		}
		
		public System.Data.Linq.Table<LUCKY_DRAW_PROGRAME_HISTORY> LUCKY_DRAW_PROGRAME_HISTORies
		{
			get
			{
				return this.GetTable<LUCKY_DRAW_PROGRAME_HISTORY>();
			}
		}
		
		public System.Data.Linq.Table<LUCKY_DRAW_KOKAKU> LUCKY_DRAW_KOKAKUs
		{
			get
			{
				return this.GetTable<LUCKY_DRAW_KOKAKU>();
			}
		}
		
		public System.Data.Linq.Table<LUCKY_DRAW_MEISAI> LUCKY_DRAW_MEISAIs
		{
			get
			{
				return this.GetTable<LUCKY_DRAW_MEISAI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUCKY_DRAW")]
	public partial class LUCKY_DRAW : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LUCKY_DRAW_ID;
		
		private string _LUCKY_DRAW_NAME;
		
		private string _LUCKY_DRAW_BUNRUI;
		
		private string _LUCKY_DRAW_TITLE;
		
		private string _LUCKY_DRAW_SLOGAN;
		
		private System.Data.Linq.Binary _LUCKY_DRAW_BG_IMG;
		
		private int _LUCKY_DRAW_SLOT_NUM;
		
		private System.DateTime _TOROKU_DATE;
		
		private string _TOROKU_ID;
		
		private string _KOSIN_NAIYOU;
		
		private System.Nullable<System.DateTime> _KOSIN_DATE;
		
		private string _KOSIN_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLUCKY_DRAW_IDChanging(string value);
    partial void OnLUCKY_DRAW_IDChanged();
    partial void OnLUCKY_DRAW_NAMEChanging(string value);
    partial void OnLUCKY_DRAW_NAMEChanged();
    partial void OnLUCKY_DRAW_BUNRUIChanging(string value);
    partial void OnLUCKY_DRAW_BUNRUIChanged();
    partial void OnLUCKY_DRAW_TITLEChanging(string value);
    partial void OnLUCKY_DRAW_TITLEChanged();
    partial void OnLUCKY_DRAW_SLOGANChanging(string value);
    partial void OnLUCKY_DRAW_SLOGANChanged();
    partial void OnLUCKY_DRAW_BG_IMGChanging(System.Data.Linq.Binary value);
    partial void OnLUCKY_DRAW_BG_IMGChanged();
    partial void OnLUCKY_DRAW_SLOT_NUMChanging(int value);
    partial void OnLUCKY_DRAW_SLOT_NUMChanged();
    partial void OnTOROKU_DATEChanging(System.DateTime value);
    partial void OnTOROKU_DATEChanged();
    partial void OnTOROKU_IDChanging(string value);
    partial void OnTOROKU_IDChanged();
    partial void OnKOSIN_NAIYOUChanging(string value);
    partial void OnKOSIN_NAIYOUChanged();
    partial void OnKOSIN_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKOSIN_DATEChanged();
    partial void OnKOSIN_IDChanging(string value);
    partial void OnKOSIN_IDChanged();
    #endregion
		
		public LUCKY_DRAW()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_ID
		{
			get
			{
				return this._LUCKY_DRAW_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_ID != value))
				{
					this.OnLUCKY_DRAW_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_ID");
					this.OnLUCKY_DRAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_NAME", DbType="NVarChar(250)")]
		public string LUCKY_DRAW_NAME
		{
			get
			{
				return this._LUCKY_DRAW_NAME;
			}
			set
			{
				if ((this._LUCKY_DRAW_NAME != value))
				{
					this.OnLUCKY_DRAW_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_NAME = value;
					this.SendPropertyChanged("LUCKY_DRAW_NAME");
					this.OnLUCKY_DRAW_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_BUNRUI", DbType="VarChar(50)")]
		public string LUCKY_DRAW_BUNRUI
		{
			get
			{
				return this._LUCKY_DRAW_BUNRUI;
			}
			set
			{
				if ((this._LUCKY_DRAW_BUNRUI != value))
				{
					this.OnLUCKY_DRAW_BUNRUIChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_BUNRUI = value;
					this.SendPropertyChanged("LUCKY_DRAW_BUNRUI");
					this.OnLUCKY_DRAW_BUNRUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_TITLE", DbType="NVarChar(250)")]
		public string LUCKY_DRAW_TITLE
		{
			get
			{
				return this._LUCKY_DRAW_TITLE;
			}
			set
			{
				if ((this._LUCKY_DRAW_TITLE != value))
				{
					this.OnLUCKY_DRAW_TITLEChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_TITLE = value;
					this.SendPropertyChanged("LUCKY_DRAW_TITLE");
					this.OnLUCKY_DRAW_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_SLOGAN", DbType="NVarChar(250)")]
		public string LUCKY_DRAW_SLOGAN
		{
			get
			{
				return this._LUCKY_DRAW_SLOGAN;
			}
			set
			{
				if ((this._LUCKY_DRAW_SLOGAN != value))
				{
					this.OnLUCKY_DRAW_SLOGANChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_SLOGAN = value;
					this.SendPropertyChanged("LUCKY_DRAW_SLOGAN");
					this.OnLUCKY_DRAW_SLOGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_BG_IMG", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LUCKY_DRAW_BG_IMG
		{
			get
			{
				return this._LUCKY_DRAW_BG_IMG;
			}
			set
			{
				if ((this._LUCKY_DRAW_BG_IMG != value))
				{
					this.OnLUCKY_DRAW_BG_IMGChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_BG_IMG = value;
					this.SendPropertyChanged("LUCKY_DRAW_BG_IMG");
					this.OnLUCKY_DRAW_BG_IMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_SLOT_NUM", DbType="Int NOT NULL")]
		public int LUCKY_DRAW_SLOT_NUM
		{
			get
			{
				return this._LUCKY_DRAW_SLOT_NUM;
			}
			set
			{
				if ((this._LUCKY_DRAW_SLOT_NUM != value))
				{
					this.OnLUCKY_DRAW_SLOT_NUMChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_SLOT_NUM = value;
					this.SendPropertyChanged("LUCKY_DRAW_SLOT_NUM");
					this.OnLUCKY_DRAW_SLOT_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime TOROKU_DATE
		{
			get
			{
				return this._TOROKU_DATE;
			}
			set
			{
				if ((this._TOROKU_DATE != value))
				{
					this.OnTOROKU_DATEChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_DATE = value;
					this.SendPropertyChanged("TOROKU_DATE");
					this.OnTOROKU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string TOROKU_ID
		{
			get
			{
				return this._TOROKU_ID;
			}
			set
			{
				if ((this._TOROKU_ID != value))
				{
					this.OnTOROKU_IDChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_ID = value;
					this.SendPropertyChanged("TOROKU_ID");
					this.OnTOROKU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_NAIYOU", DbType="NVarChar(500)")]
		public string KOSIN_NAIYOU
		{
			get
			{
				return this._KOSIN_NAIYOU;
			}
			set
			{
				if ((this._KOSIN_NAIYOU != value))
				{
					this.OnKOSIN_NAIYOUChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_NAIYOU = value;
					this.SendPropertyChanged("KOSIN_NAIYOU");
					this.OnKOSIN_NAIYOUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KOSIN_DATE
		{
			get
			{
				return this._KOSIN_DATE;
			}
			set
			{
				if ((this._KOSIN_DATE != value))
				{
					this.OnKOSIN_DATEChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_DATE = value;
					this.SendPropertyChanged("KOSIN_DATE");
					this.OnKOSIN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string KOSIN_ID
		{
			get
			{
				return this._KOSIN_ID;
			}
			set
			{
				if ((this._KOSIN_ID != value))
				{
					this.OnKOSIN_IDChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_ID = value;
					this.SendPropertyChanged("KOSIN_ID");
					this.OnKOSIN_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUCKY_DRAW_PROGRAME")]
	public partial class LUCKY_DRAW_PROGRAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LUCKY_DRAW_PROGRAME_ID;
		
		private string _LUCKY_DRAW_PROGRAME_NAME;
		
		private string _LUCKY_DRAW_ID;
		
		private System.Nullable<System.DateTime> _KAISHI_DATE;
		
		private System.Nullable<System.DateTime> _SYURYOU_DATE;
		
		private string _PROGRAME_SLOGAN;
		
		private System.DateTime _TOROKU_DATE;
		
		private string _TOROKU_ID;
		
		private string _KOSIN_NAIYOU;
		
		private System.Nullable<System.DateTime> _KOSIN_DATE;
		
		private string _KOSIN_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLUCKY_DRAW_PROGRAME_IDChanging(string value);
    partial void OnLUCKY_DRAW_PROGRAME_IDChanged();
    partial void OnLUCKY_DRAW_PROGRAME_NAMEChanging(string value);
    partial void OnLUCKY_DRAW_PROGRAME_NAMEChanged();
    partial void OnLUCKY_DRAW_IDChanging(string value);
    partial void OnLUCKY_DRAW_IDChanged();
    partial void OnKAISHI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKAISHI_DATEChanged();
    partial void OnSYURYOU_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYURYOU_DATEChanged();
    partial void OnPROGRAME_SLOGANChanging(string value);
    partial void OnPROGRAME_SLOGANChanged();
    partial void OnTOROKU_DATEChanging(System.DateTime value);
    partial void OnTOROKU_DATEChanged();
    partial void OnTOROKU_IDChanging(string value);
    partial void OnTOROKU_IDChanged();
    partial void OnKOSIN_NAIYOUChanging(string value);
    partial void OnKOSIN_NAIYOUChanged();
    partial void OnKOSIN_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKOSIN_DATEChanged();
    partial void OnKOSIN_IDChanging(string value);
    partial void OnKOSIN_IDChanged();
    #endregion
		
		public LUCKY_DRAW_PROGRAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_PROGRAME_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_PROGRAME_ID
		{
			get
			{
				return this._LUCKY_DRAW_PROGRAME_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_PROGRAME_ID != value))
				{
					this.OnLUCKY_DRAW_PROGRAME_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_PROGRAME_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_PROGRAME_ID");
					this.OnLUCKY_DRAW_PROGRAME_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_PROGRAME_NAME", DbType="NVarChar(250)")]
		public string LUCKY_DRAW_PROGRAME_NAME
		{
			get
			{
				return this._LUCKY_DRAW_PROGRAME_NAME;
			}
			set
			{
				if ((this._LUCKY_DRAW_PROGRAME_NAME != value))
				{
					this.OnLUCKY_DRAW_PROGRAME_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_PROGRAME_NAME = value;
					this.SendPropertyChanged("LUCKY_DRAW_PROGRAME_NAME");
					this.OnLUCKY_DRAW_PROGRAME_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LUCKY_DRAW_ID
		{
			get
			{
				return this._LUCKY_DRAW_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_ID != value))
				{
					this.OnLUCKY_DRAW_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_ID");
					this.OnLUCKY_DRAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAISHI_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> KAISHI_DATE
		{
			get
			{
				return this._KAISHI_DATE;
			}
			set
			{
				if ((this._KAISHI_DATE != value))
				{
					this.OnKAISHI_DATEChanging(value);
					this.SendPropertyChanging();
					this._KAISHI_DATE = value;
					this.SendPropertyChanged("KAISHI_DATE");
					this.OnKAISHI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYURYOU_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> SYURYOU_DATE
		{
			get
			{
				return this._SYURYOU_DATE;
			}
			set
			{
				if ((this._SYURYOU_DATE != value))
				{
					this.OnSYURYOU_DATEChanging(value);
					this.SendPropertyChanging();
					this._SYURYOU_DATE = value;
					this.SendPropertyChanged("SYURYOU_DATE");
					this.OnSYURYOU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAME_SLOGAN", DbType="NVarChar(250)")]
		public string PROGRAME_SLOGAN
		{
			get
			{
				return this._PROGRAME_SLOGAN;
			}
			set
			{
				if ((this._PROGRAME_SLOGAN != value))
				{
					this.OnPROGRAME_SLOGANChanging(value);
					this.SendPropertyChanging();
					this._PROGRAME_SLOGAN = value;
					this.SendPropertyChanged("PROGRAME_SLOGAN");
					this.OnPROGRAME_SLOGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime TOROKU_DATE
		{
			get
			{
				return this._TOROKU_DATE;
			}
			set
			{
				if ((this._TOROKU_DATE != value))
				{
					this.OnTOROKU_DATEChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_DATE = value;
					this.SendPropertyChanged("TOROKU_DATE");
					this.OnTOROKU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string TOROKU_ID
		{
			get
			{
				return this._TOROKU_ID;
			}
			set
			{
				if ((this._TOROKU_ID != value))
				{
					this.OnTOROKU_IDChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_ID = value;
					this.SendPropertyChanged("TOROKU_ID");
					this.OnTOROKU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_NAIYOU", DbType="NVarChar(500)")]
		public string KOSIN_NAIYOU
		{
			get
			{
				return this._KOSIN_NAIYOU;
			}
			set
			{
				if ((this._KOSIN_NAIYOU != value))
				{
					this.OnKOSIN_NAIYOUChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_NAIYOU = value;
					this.SendPropertyChanged("KOSIN_NAIYOU");
					this.OnKOSIN_NAIYOUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KOSIN_DATE
		{
			get
			{
				return this._KOSIN_DATE;
			}
			set
			{
				if ((this._KOSIN_DATE != value))
				{
					this.OnKOSIN_DATEChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_DATE = value;
					this.SendPropertyChanged("KOSIN_DATE");
					this.OnKOSIN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string KOSIN_ID
		{
			get
			{
				return this._KOSIN_ID;
			}
			set
			{
				if ((this._KOSIN_ID != value))
				{
					this.OnKOSIN_IDChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_ID = value;
					this.SendPropertyChanged("KOSIN_ID");
					this.OnKOSIN_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUCKY_DRAW_PROGRAME_HISTORY")]
	public partial class LUCKY_DRAW_PROGRAME_HISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _PROGRAME_JISSHI_ID;
		
		private string _LUCKY_DRAW_PROGRAME_ID;
		
		private string _LUCKY_DRAW_ID;
		
		private string _MITUMORI_NO_SANSYO;
		
		private string _KOKAKU_HITO_NAME;
		
		private string _KOKAKU_HITO_PHONE;
		
		private string _KOKAKU_HITO_ADDRESS;
		
		private string _RATE_LOG_SPLIT;
		
		private string _KENSYO_DRAW_MEISAI_ID;
		
		private string _KENSYO_VOUCHER_CODE;
		
		private System.Nullable<double> _KENSYO_DRAW_MEISAI_SURYO;
		
		private System.Nullable<System.DateTime> _KAISHI_DATE;
		
		private System.Nullable<System.DateTime> _SYURYOU_DATE;
		
		private System.DateTime _TOROKU_DATE;
		
		private string _TOROKU_ID;
		
		private System.Nullable<System.DateTime> _JISSHI_KAISHI_DATE;
		
		private System.Nullable<System.DateTime> _JISSHI_SYURYOU_DATE;
		
		private System.Data.Linq.Binary _MAE_JISSHI_BG_IMG;
		
		private System.Data.Linq.Binary _ATO_JISSHI_BG_IMG;
		
		private string _KOKAKU_NAME_SYUTOKU;
		
		private string _KOKAKU_PHONE_SYUTOKU;
		
		private string _KOKAKU_SHOUMEISYO_NO_SYUTOKU;
		
		private string _KOKAKU_ADDRESS_SYUTOKU;
		
		private System.Nullable<System.DateTime> _KOKAKU_SYUTOKU_DATE;
		
		private string _TANTO_SYA_NAME;
		
		private string _MITUMORI_NO_SYUTOKU_SANSYO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPROGRAME_JISSHI_IDChanging(decimal value);
    partial void OnPROGRAME_JISSHI_IDChanged();
    partial void OnLUCKY_DRAW_PROGRAME_IDChanging(string value);
    partial void OnLUCKY_DRAW_PROGRAME_IDChanged();
    partial void OnLUCKY_DRAW_IDChanging(string value);
    partial void OnLUCKY_DRAW_IDChanged();
    partial void OnMITUMORI_NO_SANSYOChanging(string value);
    partial void OnMITUMORI_NO_SANSYOChanged();
    partial void OnKOKAKU_HITO_NAMEChanging(string value);
    partial void OnKOKAKU_HITO_NAMEChanged();
    partial void OnKOKAKU_HITO_PHONEChanging(string value);
    partial void OnKOKAKU_HITO_PHONEChanged();
    partial void OnKOKAKU_HITO_ADDRESSChanging(string value);
    partial void OnKOKAKU_HITO_ADDRESSChanged();
    partial void OnRATE_LOG_SPLITChanging(string value);
    partial void OnRATE_LOG_SPLITChanged();
    partial void OnKENSYO_DRAW_MEISAI_IDChanging(string value);
    partial void OnKENSYO_DRAW_MEISAI_IDChanged();
    partial void OnKENSYO_VOUCHER_CODEChanging(string value);
    partial void OnKENSYO_VOUCHER_CODEChanged();
    partial void OnKENSYO_DRAW_MEISAI_SURYOChanging(System.Nullable<double> value);
    partial void OnKENSYO_DRAW_MEISAI_SURYOChanged();
    partial void OnKAISHI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKAISHI_DATEChanged();
    partial void OnSYURYOU_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYURYOU_DATEChanged();
    partial void OnTOROKU_DATEChanging(System.DateTime value);
    partial void OnTOROKU_DATEChanged();
    partial void OnTOROKU_IDChanging(string value);
    partial void OnTOROKU_IDChanged();
    partial void OnJISSHI_KAISHI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnJISSHI_KAISHI_DATEChanged();
    partial void OnJISSHI_SYURYOU_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnJISSHI_SYURYOU_DATEChanged();
    partial void OnMAE_JISSHI_BG_IMGChanging(System.Data.Linq.Binary value);
    partial void OnMAE_JISSHI_BG_IMGChanged();
    partial void OnATO_JISSHI_BG_IMGChanging(System.Data.Linq.Binary value);
    partial void OnATO_JISSHI_BG_IMGChanged();
    partial void OnKOKAKU_NAME_SYUTOKUChanging(string value);
    partial void OnKOKAKU_NAME_SYUTOKUChanged();
    partial void OnKOKAKU_PHONE_SYUTOKUChanging(string value);
    partial void OnKOKAKU_PHONE_SYUTOKUChanged();
    partial void OnKOKAKU_SHOUMEISYO_NO_SYUTOKUChanging(string value);
    partial void OnKOKAKU_SHOUMEISYO_NO_SYUTOKUChanged();
    partial void OnKOKAKU_ADDRESS_SYUTOKUChanging(string value);
    partial void OnKOKAKU_ADDRESS_SYUTOKUChanged();
    partial void OnKOKAKU_SYUTOKU_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKOKAKU_SYUTOKU_DATEChanged();
    partial void OnTANTO_SYA_NAMEChanging(string value);
    partial void OnTANTO_SYA_NAMEChanged();
    partial void OnMITUMORI_NO_SYUTOKU_SANSYOChanging(string value);
    partial void OnMITUMORI_NO_SYUTOKU_SANSYOChanged();
    #endregion
		
		public LUCKY_DRAW_PROGRAME_HISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROGRAME_JISSHI_ID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal PROGRAME_JISSHI_ID
		{
			get
			{
				return this._PROGRAME_JISSHI_ID;
			}
			set
			{
				if ((this._PROGRAME_JISSHI_ID != value))
				{
					this.OnPROGRAME_JISSHI_IDChanging(value);
					this.SendPropertyChanging();
					this._PROGRAME_JISSHI_ID = value;
					this.SendPropertyChanged("PROGRAME_JISSHI_ID");
					this.OnPROGRAME_JISSHI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_PROGRAME_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_PROGRAME_ID
		{
			get
			{
				return this._LUCKY_DRAW_PROGRAME_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_PROGRAME_ID != value))
				{
					this.OnLUCKY_DRAW_PROGRAME_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_PROGRAME_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_PROGRAME_ID");
					this.OnLUCKY_DRAW_PROGRAME_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_ID
		{
			get
			{
				return this._LUCKY_DRAW_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_ID != value))
				{
					this.OnLUCKY_DRAW_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_ID");
					this.OnLUCKY_DRAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MITUMORI_NO_SANSYO", DbType="VarChar(14)")]
		public string MITUMORI_NO_SANSYO
		{
			get
			{
				return this._MITUMORI_NO_SANSYO;
			}
			set
			{
				if ((this._MITUMORI_NO_SANSYO != value))
				{
					this.OnMITUMORI_NO_SANSYOChanging(value);
					this.SendPropertyChanging();
					this._MITUMORI_NO_SANSYO = value;
					this.SendPropertyChanged("MITUMORI_NO_SANSYO");
					this.OnMITUMORI_NO_SANSYOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_HITO_NAME", DbType="NVarChar(150)")]
		public string KOKAKU_HITO_NAME
		{
			get
			{
				return this._KOKAKU_HITO_NAME;
			}
			set
			{
				if ((this._KOKAKU_HITO_NAME != value))
				{
					this.OnKOKAKU_HITO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_HITO_NAME = value;
					this.SendPropertyChanged("KOKAKU_HITO_NAME");
					this.OnKOKAKU_HITO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_HITO_PHONE", DbType="VarChar(50)")]
		public string KOKAKU_HITO_PHONE
		{
			get
			{
				return this._KOKAKU_HITO_PHONE;
			}
			set
			{
				if ((this._KOKAKU_HITO_PHONE != value))
				{
					this.OnKOKAKU_HITO_PHONEChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_HITO_PHONE = value;
					this.SendPropertyChanged("KOKAKU_HITO_PHONE");
					this.OnKOKAKU_HITO_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_HITO_ADDRESS", DbType="NVarChar(250)")]
		public string KOKAKU_HITO_ADDRESS
		{
			get
			{
				return this._KOKAKU_HITO_ADDRESS;
			}
			set
			{
				if ((this._KOKAKU_HITO_ADDRESS != value))
				{
					this.OnKOKAKU_HITO_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_HITO_ADDRESS = value;
					this.SendPropertyChanged("KOKAKU_HITO_ADDRESS");
					this.OnKOKAKU_HITO_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RATE_LOG_SPLIT", DbType="VarChar(2500)")]
		public string RATE_LOG_SPLIT
		{
			get
			{
				return this._RATE_LOG_SPLIT;
			}
			set
			{
				if ((this._RATE_LOG_SPLIT != value))
				{
					this.OnRATE_LOG_SPLITChanging(value);
					this.SendPropertyChanging();
					this._RATE_LOG_SPLIT = value;
					this.SendPropertyChanged("RATE_LOG_SPLIT");
					this.OnRATE_LOG_SPLITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KENSYO_DRAW_MEISAI_ID", DbType="VarChar(50)")]
		public string KENSYO_DRAW_MEISAI_ID
		{
			get
			{
				return this._KENSYO_DRAW_MEISAI_ID;
			}
			set
			{
				if ((this._KENSYO_DRAW_MEISAI_ID != value))
				{
					this.OnKENSYO_DRAW_MEISAI_IDChanging(value);
					this.SendPropertyChanging();
					this._KENSYO_DRAW_MEISAI_ID = value;
					this.SendPropertyChanged("KENSYO_DRAW_MEISAI_ID");
					this.OnKENSYO_DRAW_MEISAI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KENSYO_VOUCHER_CODE", DbType="VarChar(50)")]
		public string KENSYO_VOUCHER_CODE
		{
			get
			{
				return this._KENSYO_VOUCHER_CODE;
			}
			set
			{
				if ((this._KENSYO_VOUCHER_CODE != value))
				{
					this.OnKENSYO_VOUCHER_CODEChanging(value);
					this.SendPropertyChanging();
					this._KENSYO_VOUCHER_CODE = value;
					this.SendPropertyChanged("KENSYO_VOUCHER_CODE");
					this.OnKENSYO_VOUCHER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KENSYO_DRAW_MEISAI_SURYO", DbType="Float")]
		public System.Nullable<double> KENSYO_DRAW_MEISAI_SURYO
		{
			get
			{
				return this._KENSYO_DRAW_MEISAI_SURYO;
			}
			set
			{
				if ((this._KENSYO_DRAW_MEISAI_SURYO != value))
				{
					this.OnKENSYO_DRAW_MEISAI_SURYOChanging(value);
					this.SendPropertyChanging();
					this._KENSYO_DRAW_MEISAI_SURYO = value;
					this.SendPropertyChanged("KENSYO_DRAW_MEISAI_SURYO");
					this.OnKENSYO_DRAW_MEISAI_SURYOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAISHI_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> KAISHI_DATE
		{
			get
			{
				return this._KAISHI_DATE;
			}
			set
			{
				if ((this._KAISHI_DATE != value))
				{
					this.OnKAISHI_DATEChanging(value);
					this.SendPropertyChanging();
					this._KAISHI_DATE = value;
					this.SendPropertyChanged("KAISHI_DATE");
					this.OnKAISHI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYURYOU_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> SYURYOU_DATE
		{
			get
			{
				return this._SYURYOU_DATE;
			}
			set
			{
				if ((this._SYURYOU_DATE != value))
				{
					this.OnSYURYOU_DATEChanging(value);
					this.SendPropertyChanging();
					this._SYURYOU_DATE = value;
					this.SendPropertyChanged("SYURYOU_DATE");
					this.OnSYURYOU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime TOROKU_DATE
		{
			get
			{
				return this._TOROKU_DATE;
			}
			set
			{
				if ((this._TOROKU_DATE != value))
				{
					this.OnTOROKU_DATEChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_DATE = value;
					this.SendPropertyChanged("TOROKU_DATE");
					this.OnTOROKU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string TOROKU_ID
		{
			get
			{
				return this._TOROKU_ID;
			}
			set
			{
				if ((this._TOROKU_ID != value))
				{
					this.OnTOROKU_IDChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_ID = value;
					this.SendPropertyChanged("TOROKU_ID");
					this.OnTOROKU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JISSHI_KAISHI_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> JISSHI_KAISHI_DATE
		{
			get
			{
				return this._JISSHI_KAISHI_DATE;
			}
			set
			{
				if ((this._JISSHI_KAISHI_DATE != value))
				{
					this.OnJISSHI_KAISHI_DATEChanging(value);
					this.SendPropertyChanging();
					this._JISSHI_KAISHI_DATE = value;
					this.SendPropertyChanged("JISSHI_KAISHI_DATE");
					this.OnJISSHI_KAISHI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JISSHI_SYURYOU_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> JISSHI_SYURYOU_DATE
		{
			get
			{
				return this._JISSHI_SYURYOU_DATE;
			}
			set
			{
				if ((this._JISSHI_SYURYOU_DATE != value))
				{
					this.OnJISSHI_SYURYOU_DATEChanging(value);
					this.SendPropertyChanging();
					this._JISSHI_SYURYOU_DATE = value;
					this.SendPropertyChanged("JISSHI_SYURYOU_DATE");
					this.OnJISSHI_SYURYOU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAE_JISSHI_BG_IMG", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary MAE_JISSHI_BG_IMG
		{
			get
			{
				return this._MAE_JISSHI_BG_IMG;
			}
			set
			{
				if ((this._MAE_JISSHI_BG_IMG != value))
				{
					this.OnMAE_JISSHI_BG_IMGChanging(value);
					this.SendPropertyChanging();
					this._MAE_JISSHI_BG_IMG = value;
					this.SendPropertyChanged("MAE_JISSHI_BG_IMG");
					this.OnMAE_JISSHI_BG_IMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATO_JISSHI_BG_IMG", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ATO_JISSHI_BG_IMG
		{
			get
			{
				return this._ATO_JISSHI_BG_IMG;
			}
			set
			{
				if ((this._ATO_JISSHI_BG_IMG != value))
				{
					this.OnATO_JISSHI_BG_IMGChanging(value);
					this.SendPropertyChanging();
					this._ATO_JISSHI_BG_IMG = value;
					this.SendPropertyChanged("ATO_JISSHI_BG_IMG");
					this.OnATO_JISSHI_BG_IMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_NAME_SYUTOKU", DbType="NVarChar(150)")]
		public string KOKAKU_NAME_SYUTOKU
		{
			get
			{
				return this._KOKAKU_NAME_SYUTOKU;
			}
			set
			{
				if ((this._KOKAKU_NAME_SYUTOKU != value))
				{
					this.OnKOKAKU_NAME_SYUTOKUChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_NAME_SYUTOKU = value;
					this.SendPropertyChanged("KOKAKU_NAME_SYUTOKU");
					this.OnKOKAKU_NAME_SYUTOKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_PHONE_SYUTOKU", DbType="VarChar(50)")]
		public string KOKAKU_PHONE_SYUTOKU
		{
			get
			{
				return this._KOKAKU_PHONE_SYUTOKU;
			}
			set
			{
				if ((this._KOKAKU_PHONE_SYUTOKU != value))
				{
					this.OnKOKAKU_PHONE_SYUTOKUChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_PHONE_SYUTOKU = value;
					this.SendPropertyChanged("KOKAKU_PHONE_SYUTOKU");
					this.OnKOKAKU_PHONE_SYUTOKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_SHOUMEISYO_NO_SYUTOKU", DbType="VarChar(50)")]
		public string KOKAKU_SHOUMEISYO_NO_SYUTOKU
		{
			get
			{
				return this._KOKAKU_SHOUMEISYO_NO_SYUTOKU;
			}
			set
			{
				if ((this._KOKAKU_SHOUMEISYO_NO_SYUTOKU != value))
				{
					this.OnKOKAKU_SHOUMEISYO_NO_SYUTOKUChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_SHOUMEISYO_NO_SYUTOKU = value;
					this.SendPropertyChanged("KOKAKU_SHOUMEISYO_NO_SYUTOKU");
					this.OnKOKAKU_SHOUMEISYO_NO_SYUTOKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_ADDRESS_SYUTOKU", DbType="VarChar(50)")]
		public string KOKAKU_ADDRESS_SYUTOKU
		{
			get
			{
				return this._KOKAKU_ADDRESS_SYUTOKU;
			}
			set
			{
				if ((this._KOKAKU_ADDRESS_SYUTOKU != value))
				{
					this.OnKOKAKU_ADDRESS_SYUTOKUChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_ADDRESS_SYUTOKU = value;
					this.SendPropertyChanged("KOKAKU_ADDRESS_SYUTOKU");
					this.OnKOKAKU_ADDRESS_SYUTOKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_SYUTOKU_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KOKAKU_SYUTOKU_DATE
		{
			get
			{
				return this._KOKAKU_SYUTOKU_DATE;
			}
			set
			{
				if ((this._KOKAKU_SYUTOKU_DATE != value))
				{
					this.OnKOKAKU_SYUTOKU_DATEChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_SYUTOKU_DATE = value;
					this.SendPropertyChanged("KOKAKU_SYUTOKU_DATE");
					this.OnKOKAKU_SYUTOKU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANTO_SYA_NAME", DbType="NVarChar(150)")]
		public string TANTO_SYA_NAME
		{
			get
			{
				return this._TANTO_SYA_NAME;
			}
			set
			{
				if ((this._TANTO_SYA_NAME != value))
				{
					this.OnTANTO_SYA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TANTO_SYA_NAME = value;
					this.SendPropertyChanged("TANTO_SYA_NAME");
					this.OnTANTO_SYA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MITUMORI_NO_SYUTOKU_SANSYO", DbType="VarChar(14)")]
		public string MITUMORI_NO_SYUTOKU_SANSYO
		{
			get
			{
				return this._MITUMORI_NO_SYUTOKU_SANSYO;
			}
			set
			{
				if ((this._MITUMORI_NO_SYUTOKU_SANSYO != value))
				{
					this.OnMITUMORI_NO_SYUTOKU_SANSYOChanging(value);
					this.SendPropertyChanging();
					this._MITUMORI_NO_SYUTOKU_SANSYO = value;
					this.SendPropertyChanged("MITUMORI_NO_SYUTOKU_SANSYO");
					this.OnMITUMORI_NO_SYUTOKU_SANSYOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUCKY_DRAW_KOKAKU")]
	public partial class LUCKY_DRAW_KOKAKU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LUCKY_DRAW_ID;
		
		private string _KOKAKU_HITO_PHONE;
		
		private string _KOKAKU_HITO_NAME;
		
		private System.Data.Linq.Binary _KOKAKU_HITO_IMG;
		
		private string _KOKAKU_ADDRESS;
		
		private string _KOKAKU_SHOUMEISYO_NO;
		
		private System.Nullable<int> _KOKAKU_MUKO_FLG;
		
		private System.DateTime _TOROKU_DATE;
		
		private string _TOROKU_ID;
		
		private string _KOSIN_NAIYOU;
		
		private System.Nullable<System.DateTime> _KOSIN_DATE;
		
		private string _KOSIN_ID;
		
		private System.Nullable<System.DateTime> _KAISHI_DATE;
		
		private System.Nullable<System.DateTime> _SYURYOU_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLUCKY_DRAW_IDChanging(string value);
    partial void OnLUCKY_DRAW_IDChanged();
    partial void OnKOKAKU_HITO_PHONEChanging(string value);
    partial void OnKOKAKU_HITO_PHONEChanged();
    partial void OnKOKAKU_HITO_NAMEChanging(string value);
    partial void OnKOKAKU_HITO_NAMEChanged();
    partial void OnKOKAKU_HITO_IMGChanging(System.Data.Linq.Binary value);
    partial void OnKOKAKU_HITO_IMGChanged();
    partial void OnKOKAKU_ADDRESSChanging(string value);
    partial void OnKOKAKU_ADDRESSChanged();
    partial void OnKOKAKU_SHOUMEISYO_NOChanging(string value);
    partial void OnKOKAKU_SHOUMEISYO_NOChanged();
    partial void OnKOKAKU_MUKO_FLGChanging(System.Nullable<int> value);
    partial void OnKOKAKU_MUKO_FLGChanged();
    partial void OnTOROKU_DATEChanging(System.DateTime value);
    partial void OnTOROKU_DATEChanged();
    partial void OnTOROKU_IDChanging(string value);
    partial void OnTOROKU_IDChanged();
    partial void OnKOSIN_NAIYOUChanging(string value);
    partial void OnKOSIN_NAIYOUChanged();
    partial void OnKOSIN_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKOSIN_DATEChanged();
    partial void OnKOSIN_IDChanging(string value);
    partial void OnKOSIN_IDChanged();
    partial void OnKAISHI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKAISHI_DATEChanged();
    partial void OnSYURYOU_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYURYOU_DATEChanged();
    #endregion
		
		public LUCKY_DRAW_KOKAKU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_ID
		{
			get
			{
				return this._LUCKY_DRAW_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_ID != value))
				{
					this.OnLUCKY_DRAW_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_ID");
					this.OnLUCKY_DRAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_HITO_PHONE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KOKAKU_HITO_PHONE
		{
			get
			{
				return this._KOKAKU_HITO_PHONE;
			}
			set
			{
				if ((this._KOKAKU_HITO_PHONE != value))
				{
					this.OnKOKAKU_HITO_PHONEChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_HITO_PHONE = value;
					this.SendPropertyChanged("KOKAKU_HITO_PHONE");
					this.OnKOKAKU_HITO_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_HITO_NAME", DbType="NVarChar(50)")]
		public string KOKAKU_HITO_NAME
		{
			get
			{
				return this._KOKAKU_HITO_NAME;
			}
			set
			{
				if ((this._KOKAKU_HITO_NAME != value))
				{
					this.OnKOKAKU_HITO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_HITO_NAME = value;
					this.SendPropertyChanged("KOKAKU_HITO_NAME");
					this.OnKOKAKU_HITO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_HITO_IMG", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary KOKAKU_HITO_IMG
		{
			get
			{
				return this._KOKAKU_HITO_IMG;
			}
			set
			{
				if ((this._KOKAKU_HITO_IMG != value))
				{
					this.OnKOKAKU_HITO_IMGChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_HITO_IMG = value;
					this.SendPropertyChanged("KOKAKU_HITO_IMG");
					this.OnKOKAKU_HITO_IMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_ADDRESS", DbType="NVarChar(250)")]
		public string KOKAKU_ADDRESS
		{
			get
			{
				return this._KOKAKU_ADDRESS;
			}
			set
			{
				if ((this._KOKAKU_ADDRESS != value))
				{
					this.OnKOKAKU_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_ADDRESS = value;
					this.SendPropertyChanged("KOKAKU_ADDRESS");
					this.OnKOKAKU_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_SHOUMEISYO_NO", DbType="VarChar(50)")]
		public string KOKAKU_SHOUMEISYO_NO
		{
			get
			{
				return this._KOKAKU_SHOUMEISYO_NO;
			}
			set
			{
				if ((this._KOKAKU_SHOUMEISYO_NO != value))
				{
					this.OnKOKAKU_SHOUMEISYO_NOChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_SHOUMEISYO_NO = value;
					this.SendPropertyChanged("KOKAKU_SHOUMEISYO_NO");
					this.OnKOKAKU_SHOUMEISYO_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOKAKU_MUKO_FLG", DbType="Int")]
		public System.Nullable<int> KOKAKU_MUKO_FLG
		{
			get
			{
				return this._KOKAKU_MUKO_FLG;
			}
			set
			{
				if ((this._KOKAKU_MUKO_FLG != value))
				{
					this.OnKOKAKU_MUKO_FLGChanging(value);
					this.SendPropertyChanging();
					this._KOKAKU_MUKO_FLG = value;
					this.SendPropertyChanged("KOKAKU_MUKO_FLG");
					this.OnKOKAKU_MUKO_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime TOROKU_DATE
		{
			get
			{
				return this._TOROKU_DATE;
			}
			set
			{
				if ((this._TOROKU_DATE != value))
				{
					this.OnTOROKU_DATEChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_DATE = value;
					this.SendPropertyChanged("TOROKU_DATE");
					this.OnTOROKU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string TOROKU_ID
		{
			get
			{
				return this._TOROKU_ID;
			}
			set
			{
				if ((this._TOROKU_ID != value))
				{
					this.OnTOROKU_IDChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_ID = value;
					this.SendPropertyChanged("TOROKU_ID");
					this.OnTOROKU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_NAIYOU", DbType="NVarChar(500)")]
		public string KOSIN_NAIYOU
		{
			get
			{
				return this._KOSIN_NAIYOU;
			}
			set
			{
				if ((this._KOSIN_NAIYOU != value))
				{
					this.OnKOSIN_NAIYOUChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_NAIYOU = value;
					this.SendPropertyChanged("KOSIN_NAIYOU");
					this.OnKOSIN_NAIYOUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KOSIN_DATE
		{
			get
			{
				return this._KOSIN_DATE;
			}
			set
			{
				if ((this._KOSIN_DATE != value))
				{
					this.OnKOSIN_DATEChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_DATE = value;
					this.SendPropertyChanged("KOSIN_DATE");
					this.OnKOSIN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string KOSIN_ID
		{
			get
			{
				return this._KOSIN_ID;
			}
			set
			{
				if ((this._KOSIN_ID != value))
				{
					this.OnKOSIN_IDChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_ID = value;
					this.SendPropertyChanged("KOSIN_ID");
					this.OnKOSIN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAISHI_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> KAISHI_DATE
		{
			get
			{
				return this._KAISHI_DATE;
			}
			set
			{
				if ((this._KAISHI_DATE != value))
				{
					this.OnKAISHI_DATEChanging(value);
					this.SendPropertyChanging();
					this._KAISHI_DATE = value;
					this.SendPropertyChanged("KAISHI_DATE");
					this.OnKAISHI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYURYOU_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> SYURYOU_DATE
		{
			get
			{
				return this._SYURYOU_DATE;
			}
			set
			{
				if ((this._SYURYOU_DATE != value))
				{
					this.OnSYURYOU_DATEChanging(value);
					this.SendPropertyChanging();
					this._SYURYOU_DATE = value;
					this.SendPropertyChanged("SYURYOU_DATE");
					this.OnSYURYOU_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUCKY_DRAW_MEISAI")]
	public partial class LUCKY_DRAW_MEISAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LUCKY_DRAW_ID;
		
		private string _LUCKY_DRAW_MEISAI_NO;
		
		private string _LUCKY_DRAW_MEISAI_NAME;
		
		private string _LUCKY_DRAW_MEISAI_NAIYOU;
		
		private System.Data.Linq.Binary _LUCKY_DRAW_MEISAI_IMG;
		
		private double _LUCKY_DRAW_MEISAI_RATE;
		
		private System.Nullable<double> _LUCKY_DRAW_MEISAI_SURYO;
		
		private System.Nullable<int> _LUCKY_DRAW_MEISAI_ONSHOU_NUM;
		
		private string _LUCKY_DRAW_MEISAI_BUNRUI;
		
		private System.Nullable<int> _LUCKY_DRAW_MEISAI_MUKO_FLG;
		
		private System.DateTime _TOROKU_DATE;
		
		private string _TOROKU_ID;
		
		private string _KOSIN_NAIYOU;
		
		private System.Nullable<System.DateTime> _KOSIN_DATE;
		
		private string _KOSIN_ID;
		
		private System.Nullable<System.DateTime> _KAISHI_DATE;
		
		private System.Nullable<System.DateTime> _SYURYOU_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLUCKY_DRAW_IDChanging(string value);
    partial void OnLUCKY_DRAW_IDChanged();
    partial void OnLUCKY_DRAW_MEISAI_NOChanging(string value);
    partial void OnLUCKY_DRAW_MEISAI_NOChanged();
    partial void OnLUCKY_DRAW_MEISAI_NAMEChanging(string value);
    partial void OnLUCKY_DRAW_MEISAI_NAMEChanged();
    partial void OnLUCKY_DRAW_MEISAI_NAIYOUChanging(string value);
    partial void OnLUCKY_DRAW_MEISAI_NAIYOUChanged();
    partial void OnLUCKY_DRAW_MEISAI_IMGChanging(System.Data.Linq.Binary value);
    partial void OnLUCKY_DRAW_MEISAI_IMGChanged();
    partial void OnLUCKY_DRAW_MEISAI_RATEChanging(double value);
    partial void OnLUCKY_DRAW_MEISAI_RATEChanged();
    partial void OnLUCKY_DRAW_MEISAI_SURYOChanging(System.Nullable<double> value);
    partial void OnLUCKY_DRAW_MEISAI_SURYOChanged();
    partial void OnLUCKY_DRAW_MEISAI_ONSHOU_NUMChanging(System.Nullable<int> value);
    partial void OnLUCKY_DRAW_MEISAI_ONSHOU_NUMChanged();
    partial void OnLUCKY_DRAW_MEISAI_BUNRUIChanging(string value);
    partial void OnLUCKY_DRAW_MEISAI_BUNRUIChanged();
    partial void OnLUCKY_DRAW_MEISAI_MUKO_FLGChanging(System.Nullable<int> value);
    partial void OnLUCKY_DRAW_MEISAI_MUKO_FLGChanged();
    partial void OnTOROKU_DATEChanging(System.DateTime value);
    partial void OnTOROKU_DATEChanged();
    partial void OnTOROKU_IDChanging(string value);
    partial void OnTOROKU_IDChanged();
    partial void OnKOSIN_NAIYOUChanging(string value);
    partial void OnKOSIN_NAIYOUChanged();
    partial void OnKOSIN_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKOSIN_DATEChanged();
    partial void OnKOSIN_IDChanging(string value);
    partial void OnKOSIN_IDChanged();
    partial void OnKAISHI_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKAISHI_DATEChanged();
    partial void OnSYURYOU_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYURYOU_DATEChanged();
    #endregion
		
		public LUCKY_DRAW_MEISAI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_ID
		{
			get
			{
				return this._LUCKY_DRAW_ID;
			}
			set
			{
				if ((this._LUCKY_DRAW_ID != value))
				{
					this.OnLUCKY_DRAW_IDChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_ID = value;
					this.SendPropertyChanged("LUCKY_DRAW_ID");
					this.OnLUCKY_DRAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_NO", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LUCKY_DRAW_MEISAI_NO
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_NO;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_NO != value))
				{
					this.OnLUCKY_DRAW_MEISAI_NOChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_NO = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_NO");
					this.OnLUCKY_DRAW_MEISAI_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_NAME", DbType="NVarChar(50)")]
		public string LUCKY_DRAW_MEISAI_NAME
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_NAME;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_NAME != value))
				{
					this.OnLUCKY_DRAW_MEISAI_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_NAME = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_NAME");
					this.OnLUCKY_DRAW_MEISAI_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_NAIYOU", DbType="NVarChar(150)")]
		public string LUCKY_DRAW_MEISAI_NAIYOU
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_NAIYOU;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_NAIYOU != value))
				{
					this.OnLUCKY_DRAW_MEISAI_NAIYOUChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_NAIYOU = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_NAIYOU");
					this.OnLUCKY_DRAW_MEISAI_NAIYOUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_IMG", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LUCKY_DRAW_MEISAI_IMG
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_IMG;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_IMG != value))
				{
					this.OnLUCKY_DRAW_MEISAI_IMGChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_IMG = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_IMG");
					this.OnLUCKY_DRAW_MEISAI_IMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_RATE", DbType="Float NOT NULL")]
		public double LUCKY_DRAW_MEISAI_RATE
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_RATE;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_RATE != value))
				{
					this.OnLUCKY_DRAW_MEISAI_RATEChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_RATE = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_RATE");
					this.OnLUCKY_DRAW_MEISAI_RATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_SURYO", DbType="Float")]
		public System.Nullable<double> LUCKY_DRAW_MEISAI_SURYO
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_SURYO;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_SURYO != value))
				{
					this.OnLUCKY_DRAW_MEISAI_SURYOChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_SURYO = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_SURYO");
					this.OnLUCKY_DRAW_MEISAI_SURYOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_ONSHOU_NUM", DbType="Int")]
		public System.Nullable<int> LUCKY_DRAW_MEISAI_ONSHOU_NUM
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_ONSHOU_NUM;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_ONSHOU_NUM != value))
				{
					this.OnLUCKY_DRAW_MEISAI_ONSHOU_NUMChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_ONSHOU_NUM = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_ONSHOU_NUM");
					this.OnLUCKY_DRAW_MEISAI_ONSHOU_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_BUNRUI", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LUCKY_DRAW_MEISAI_BUNRUI
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_BUNRUI;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_BUNRUI != value))
				{
					this.OnLUCKY_DRAW_MEISAI_BUNRUIChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_BUNRUI = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_BUNRUI");
					this.OnLUCKY_DRAW_MEISAI_BUNRUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCKY_DRAW_MEISAI_MUKO_FLG", DbType="Int")]
		public System.Nullable<int> LUCKY_DRAW_MEISAI_MUKO_FLG
		{
			get
			{
				return this._LUCKY_DRAW_MEISAI_MUKO_FLG;
			}
			set
			{
				if ((this._LUCKY_DRAW_MEISAI_MUKO_FLG != value))
				{
					this.OnLUCKY_DRAW_MEISAI_MUKO_FLGChanging(value);
					this.SendPropertyChanging();
					this._LUCKY_DRAW_MEISAI_MUKO_FLG = value;
					this.SendPropertyChanged("LUCKY_DRAW_MEISAI_MUKO_FLG");
					this.OnLUCKY_DRAW_MEISAI_MUKO_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime TOROKU_DATE
		{
			get
			{
				return this._TOROKU_DATE;
			}
			set
			{
				if ((this._TOROKU_DATE != value))
				{
					this.OnTOROKU_DATEChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_DATE = value;
					this.SendPropertyChanged("TOROKU_DATE");
					this.OnTOROKU_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOROKU_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string TOROKU_ID
		{
			get
			{
				return this._TOROKU_ID;
			}
			set
			{
				if ((this._TOROKU_ID != value))
				{
					this.OnTOROKU_IDChanging(value);
					this.SendPropertyChanging();
					this._TOROKU_ID = value;
					this.SendPropertyChanged("TOROKU_ID");
					this.OnTOROKU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_NAIYOU", DbType="NVarChar(500)")]
		public string KOSIN_NAIYOU
		{
			get
			{
				return this._KOSIN_NAIYOU;
			}
			set
			{
				if ((this._KOSIN_NAIYOU != value))
				{
					this.OnKOSIN_NAIYOUChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_NAIYOU = value;
					this.SendPropertyChanged("KOSIN_NAIYOU");
					this.OnKOSIN_NAIYOUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KOSIN_DATE
		{
			get
			{
				return this._KOSIN_DATE;
			}
			set
			{
				if ((this._KOSIN_DATE != value))
				{
					this.OnKOSIN_DATEChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_DATE = value;
					this.SendPropertyChanged("KOSIN_DATE");
					this.OnKOSIN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSIN_ID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string KOSIN_ID
		{
			get
			{
				return this._KOSIN_ID;
			}
			set
			{
				if ((this._KOSIN_ID != value))
				{
					this.OnKOSIN_IDChanging(value);
					this.SendPropertyChanging();
					this._KOSIN_ID = value;
					this.SendPropertyChanged("KOSIN_ID");
					this.OnKOSIN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAISHI_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> KAISHI_DATE
		{
			get
			{
				return this._KAISHI_DATE;
			}
			set
			{
				if ((this._KAISHI_DATE != value))
				{
					this.OnKAISHI_DATEChanging(value);
					this.SendPropertyChanging();
					this._KAISHI_DATE = value;
					this.SendPropertyChanged("KAISHI_DATE");
					this.OnKAISHI_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYURYOU_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> SYURYOU_DATE
		{
			get
			{
				return this._SYURYOU_DATE;
			}
			set
			{
				if ((this._SYURYOU_DATE != value))
				{
					this.OnSYURYOU_DATEChanging(value);
					this.SendPropertyChanging();
					this._SYURYOU_DATE = value;
					this.SendPropertyChanged("SYURYOU_DATE");
					this.OnSYURYOU_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
